### ISSUE TITLE
Blockfrost service does not contain Testnet URI for Transaction Submission endpoint 

### ISSUE THREAD

**Issue by shawnsblog** [blockfrost/blockfrost-dotnet#14]
### Contact Details

shawnsblog@gmail.com

### What happened?

After creating a CBOR via CardanoSharp to submit to Blockfrost /tx/submit endpoint 400 error message is presented.

```
"error": "Bad Request",
"message": "Network token mismatch. Are you using token for the correct network? See https://docs.blockfrost.io/#section/Available-networks.",
    "status_code": 400
```
Developers should not have to expend real ADA to test against endpoints.

### Version

v0.0.1-alpha (default)

### In what OS are you experiencing the problem?

Windows

### What version of dotnet are you using?

3.1.x

**Comment by mmahut** [comment]
The API error means you are using an incorrect token - probably using your PROJECT_ID for mainnet on an testnet endpoint?

**Comment by shawnsblog** [comment]
@mmahut there is no Testnet URI for the /tx/submit endpoint.
https://docs.blockfrost.io/#tag/Cardano-Transactions/paths/~1tx~1submit/post

**Comment by mmahut** [comment]
What do you mean? I see it here:

![Screenshot from 2021-08-12 15-20-58](https://user-images.githubusercontent.com/104795/129204061-07246599-76b3-4466-9c8e-c0ad7abdbbb0.png)

**Comment by shawnsblog** [comment]
The drop down arrow wasn't present on my UI for some reason even after multiple attempts. I apologize.

Ignore this issue then.
