### ISSUE TITLE
Question: Will this library provide transaction signing functionality too?

### ISSUE THREAD

**Issue by eddex** [blockfrost/blockfrost-dotnet#20]
I would like to be able to send transactions to the Cardano blockchain using the blockfrost API.
There is an endpoint for that: https://docs.blockfrost.io/#tag/Cardano-Transactions/paths/~1tx~1submit/post

This endpoint expects a serialized transaction. Will this library provide the logic to create the input for this endpoint or do I need to create the serialized transaction in another way?

**Comment by mmahut** [comment]
@eddex for transaction serialization you might want to look at https://github.com/CardanoSharp/cardanosharp-wallet
