### ISSUE TITLE
Improve compatibillity with CardanoSharp-Wallet

### ISSUE THREAD

**Issue by eddex** [blockfrost/blockfrost-dotnet#29]
[CardanoSharp-Wallet](https://github.com/CardanoSharp/cardanosharp-wallet) and blockfrost-dotnet combined will be a great tool to develop on the cardano blockchain. However, there's quite some room for improvements.

I wanted to create a Transaction that I previously serialized with CardanoSharp-Wallet. However, the data types of the two libraries do not match.

```C#
...
// Create serialized transaction using CardanoSharp.Wallet.Models.Transactions.Transaction
var signedTx = transaction.Serialize();

// Use blockfrost-dotnet to submit the transaction
transactionService.SubmitAsync(signedTx); // doesn't work because signedTxSerialized is byte[] but a string is expected
```

What also seems to be wrong is the way the data is transmitted. In `ABlockfrostService.SendPostRequestAsync()`, which is used for the above call to `transactionService.SubmitAsync(signedTx)`, the following code is present:

```C#
// line 345, pretty sure the StringContent doesn't work for binary data.
request_.Content = new StringContent(content, System.Text.Encoding.UTF8, "application/cbor");
```

**Comment by tweakch** [comment]
POST will be in the next release... '0.0.5`

As we move to `0.1.x` there will be an extensions for CS-Wallet to support their types before we have a major update of the API to improve DevExp with much cleaner namespaces and method names...

**Comment by eddex** [comment]
I tried to use the `.ToStringHex()` extension method of CS-Wallet, but this also doesn't seem to be correct.

```c#
transactionService.SubmitAsync(signedTxSerialized.ToStringHex())
```

The error message I get is simply `400: Bad request`. So I don't know what exactly I did wrong..

Is there an example on how the Tx has to be formatted for the blockfrost API to accept it?

**Comment by tweakch** [comment]
This is what I am going to do to test (and fix) it

```sh
xxd -r -p <<< $(jq .cborHex tx.signed) > tx.submit-api.raw
curl "https://cardano-mainnet.blockfrost.io/api/v0/tx/submit" \
  -X POST \
  -H "Content-Type: application/cbor" \
  -H "project_id: $PROJECT_ID" \
  --data-binary @./tx.submit-api.raw
```

**Comment by tweakch** [comment]
> I tried to use the .ToStringHex() extension method of CS-Wallet, but this also doesn't seem to be correct.

There was a bug with a control character at the end of the CBOR a while ago with the `ToStringHex` method.. i think it got fixed (not sure tough). I would use cardano-cli for now to sign the transaction

**Comment by tweakch** [comment]
> I tried to use the `.ToStringHex()` extension...

As you pointed out the StringContent is probably the issue ... you could try this and hope for the best 😅

```cs
var hex = signedTxSerialized.ToStringHex();
var raw = hex.HexToByteArray();
using MemoryStream stream = new MemoryStream(raw);
await transactionService.SubmitAsync(raw)
```

I on my way to the console and will try this and work from there

**Comment by tweakch** [comment]
Ok there are a couple of issues here. 

- [x] Add predefined test vectors known to work on `cardano-cli`
- [x] Create sender and receiver wallets for tests
- [x] Submit transaction via stream
- [x] Submit transaction via string 
- [x] Verify transaction submit

I opened #31 to track them

**Comment by tweakch** [comment]
We will keep this open until we release v0.1 

v0.1 will introduce an extension package `Blockfrost.Extensions.CardanoSharp` to work with both libraries

**Comment by tweakch** [comment]
Continued here https://github.com/blockfrost/blockfrost-dotnet/pull/30#pullrequestreview-735612348

**Comment by tweakch** [comment]
...nope. this is not done
