### ISSUE TITLE
Update samples and docs for v1

### ISSUE THREAD

**Issue by tweakch** [blockfrost/blockfrost-dotnet#58]
Some of the samples and documentation need to be updated in preparation for v1. 

- [X] Update [migration guide](https://github.com/blockfrost/blockfrost-dotnet/wiki/Migration-Guide)
- [ ] Update samples
- [ ] Update readme

**Comment by soyfrien** [comment]
For anyone pulling in the latest release on nuget, you should refer to the examples on nuget.org: https://www.nuget.org/packages/Blockfrost.Api/latest

The current examples in the README.md will not work.
