### ISSUE TITLE
Make `staging` the default branch

### ISSUE THREAD

**Issue by tweakch** [blockfrost/blockfrost-dotnet#6]
## Description

As expected, secrets are not passed to the runner when the PR is coming from a fork.

The difference can be seen here:
* [step 6](https://github.com/blockfrost/blockfrost-dotnet/runs/3291679787#step:6:6) of the pre-merge check of #5 
* [step 5](https://github.com/blockfrost/blockfrost-dotnet/runs/3291877068#step:5:6) of a simple commit on `master`. 

So we can only run the CI build when merging from local branches.

I am not a devops expert, but here are my suggestions on how to setup branches to streamline pull requests.

We could

- [x] rename `master` to `staging` (keep as default)
- [x] add a new branch `main` (not default) 
- [ ] run the CI builds only on `main` 
- [ ] #11

We **must** 

- [x] protect `main` and `staging` by *pull request reviews* and *status checks*
- [ ] #10

This would make it possible to setup different workflows for PRs and release / integration tests

**Comment by mmahut** [comment]
The branches are renamed and protected.
