### ISSUE TITLE
Add support for "preprod" and "preview" networks

### ISSUE THREAD

**Issue by pszeder** [blockfrost/blockfrost-dotnet#60]
Cardano introduced the new testnet environments and Blockfrost added support by providing new/different API keys for the new "preprod" and "preview" networks.

Those keys are not accepted by this library and looking at the code it also seems the API base URLs are hardcoded, so we will need an update to this package to make it work.

**Comment by lilpaul** [comment]
tried to do a PR for it, but it seems like the staging branch is quite different to the version we are using via nuget.
is there a dev process doc or something like that for getting started with contributing to the project?
seems like from looking through the code there might be some kind of generator being used maybe?

**Comment by sorki** [comment]
Done in #61.
